### PR TITLE
Send feedback #74

### PR DESCRIPTION
**Pull request by AhmedAdelIbrahim**
@renadshaaban @myriameayman @ebrahim-elgaml @som3a123 @mahatalaat @MariamTalaat Please review me

### CODE REVIEW

**Comment by ebrahim-elgaml** [comment]
@myriameayman  @AhmedAdelIbrahim  @som3a123  @renadshaaban  The task has been finished please review it as soon as possible

**Comment by myriameayman** [comment]
@AhmedAdelIbrahim , @ebrahim-elgaml  
u didn't solve all ur conflicts 
for example friend model

**Comment by ebrahim-elgaml** [comment]
@myriameayman  try now

**Comment by myriameayman** [comment]
@ebrahim-elgaml 
i didn't get a verification email 
sorry :(

**Comment by ebrahim-elgaml** [comment]
screenshot from 2015-05-07 08 49 36

**Comment by ebrahim-elgaml** [comment]
You have already received 4 emails

**Comment by AhmedAdelIbrahim** [comment]
@myriameayman all the tests are working now , check again

**Pull request merged**
