### PR TITLE
final push before demo #17

### PR DESCRIPTION
**Pull request by AhmedAdelIbrahim**

### CODE REVIEW

**Comment by AhmedAdelIbrahim** [comment]
@myriameayman  Please review before merging

**Comment by myriameayman** [comment]
@AhmedAdelIbrahim not working for me 
Sinatra issues

**Comment by AhmedAdelIbrahim** [comment]
@myriameayman there were problems with 'sinatra' and 'google-api-client' , but i handles this problem , i will push the project again and waiting for your review .

**Comment by AhmedAdelIbrahim** [comment]
@myriameayman I have pushed it and waiting for your review before merging

**Comment by AhmedAdelIbrahim** [comment]
@renadshaaban  please review me

**Comment by renadshaaban** [comment]
@AhmedAdelIbrahim it is working (Y)  , but why do we need to enter username ofsignning in

**Pull request merged**
