### PR TITLE
View friend profile

### PR DESCRIPTION
**Pull request by myriameayman**
merging issue #76 
view friend profile

### CODE REVIEW

**Comment by mahatalaat** [comment]
@myriameayman  in the profile controller please elaborate more explain precisely what does the friend_places do 
and in places view in friend places the last 3 closing tags are not commented

**Comment by myriameayman** [comment]
@mahatalaat , @MariamTalaat  done with modifications

**Comment by myriameayman** [comment]
@som3a123 plz review me 
@ebrahim-elgaml , @renadshaaban , @AhmedAdelIbrahim

**Comment by AhmedAdelIbrahim** [comment]
@myriameayman all the tests are green , i checked all the validations , great work

**Comment by renadshaaban** [comment]
@myriameayman  I can't find a UML named after the user story , make sure it exists or check its name

**Comment by aaelfiky** [comment]
@myriameayman Scenario Review :+1:

**Comment by myriameayman** [comment]
@renadshaaban sorry about that 
i forget it

**Comment by ebrahim-elgaml** [comment]
@myriameayman  
Please modify the following 
*places controller ==> friend_places  action to be spaces not taps (2 spaces not 4 )
*Circle#show view uid is identifier for facebook only not twitter and gmail 
*app/views/places/create.html.erb the loop in line 25 it end should be aligned at the correct position  under the loop
*app/views/places/friend_places.html.erb (head ,body and div  at line 25 ) tags should be moved 2 spaces to the right 
*app/views/profiles/friend_profile.html.erb (head , body and style ) tags should move 2 spaces to the right with their bodies 
*app/views/profiles/myAccount.html.erb use spaces instead of taps from line 51 to 59
*test/functional/places_controller_test.rb correct the layout

**Comment by renadshaaban** [comment]
@myriameayman  same again , sry :disappointed:

**Comment by myriameayman** [comment]
@renadshaaban :'(

**Comment by renadshaaban** [comment]
@myriameayman  finally done :dancer:

**Comment by myriameayman** [comment]
@ebrahim-elgaml 
done ? 
leltna tawila ana 7asa :P

**Comment by ebrahim-elgaml** [comment]
@myriameayman  Good job

**Comment by mahatalaat** [comment]
@myriameayman  done

**Pull request merged**
