### PR TITLE
Vie friends in circle

### PR DESCRIPTION
**Pull request by ebrahim-elgaml**
Please review (Back-end only ) #32 
@renadshaaban  
@myriameayman  
@som3a123

### CODE REVIEW

**Comment by renadshaaban** [comment]
@ebrahim-elgaml there are 2 or 3 bugs
-friends in a circle are duplicated (each occurs twice)
-if I signed in first time , added twitter to my connection and logged out , re sign in again ,  I can add twitter one more time , and have again twitter circle (twitter should disapper now )
-u didn't finish the whole scenario , now we got our friends , it doeasn't appear if they have raye7 or not , If I can invite them or not

**Comment by ebrahim-elgaml** [comment]
@renadshaaban  all the stated bugs is not in my user story except the invite and we decided that it will be delayed for now to a new user story

**Comment by ebrahim-elgaml** [comment]
@myriameayman  @renadshaaban  @AhmedAdelIbrahim  @mahatalaat  @som3a123  @MariamTalaat 
Please review

**Comment by renadshaaban** [comment]
@ebrahim-elgaml  I got this error when I sign up 
aye7-/app/views/profiles/myAccount.html.erb where line #69 
undefined method `faceboook_profileimage' for #User:0x007f802ea0b238
it didn't redirected me to fb to authenticate

**Comment by ebrahim-elgaml** [comment]
@renadshaaban  check it now

**Comment by renadshaaban** [comment]
@ebrahim-elgaml  the user story is working good ,  but I don't like the view , I think if it is centered it will be better , and also Circles#show

Find me in app/views/circles/show.html.erb , not important anymore

**Comment by mahatalaat** [comment]
@ebrahim-elgaml  please add dots in controller circle  and controller profiles (myaccount)

**Comment by ebrahim-elgaml** [comment]
@mahatalaat  please check now

**Comment by mahatalaat** [comment]
@ebrahim-elgaml  done

**Comment by ebrahim-elgaml** [comment]
@mahatalaat  please check documentation review for myAccount view

**Comment by ebrahim-elgaml** [comment]
@renadshaaban  please check the uml diagram now and add the label after finishing

**Comment by aaelfiky** [comment]
@ebrahim-elgaml UML review done (Y)

**Comment by mahatalaat** [comment]
@ebrahim-elgaml    in the myaccount view line 172 what is the </div> for , its missing the comment

**Comment by ebrahim-elgaml** [comment]
@mahatalaat  please check now

**Comment by mahatalaat** [comment]
@ebrahim-elgaml  the </div> is missing the comment

**Comment by ebrahim-elgaml** [comment]
@myriameayman  please merge pull request and close issue #32 after that

**Pull request merged**
