### PR TITLE
Adding checkpoints

### PR DESCRIPTION
**Pull request by myriameayman**

### CODE REVIEW

**Comment by mahatalaat** [comment]
@myriameayman  please in the request controller the create part explain what is the code doing .
and in request view create checkpoint you have some tags which are not documented .

**Comment by renadshaaban** [comment]
@myriameayman  I'm done with UML , good job :dancer:

**Comment by AhmedAdelIbrahim** [comment]
@myriameayman all the tests are green , all validations are covered

**Comment by ebrahim-elgaml** [comment]
@myriameayman  
Change : -
*\* app/controllers/requests_controller.rb create action from second unless [SPACES]
*\* app/models/place.rb line 5 
*\*  app/models/request.rb line 5 
*\*  app/views/requests/create_checkpoints.html.er body and head tags 
*\* app/views/requests/create_route.html.erb the script body
*\*  app/views/requests/delete.html.erb body and head

**Comment by aaelfiky** [comment]
@myriameayman Scenario done :+1:

**Comment by ebrahim-elgaml** [comment]
Done

**Pull request merged**
