### PR TITLE
Create email circle

### PR DESCRIPTION
**Pull request by ebrahim-elgaml**
@myriameayman  @renadshaaban  @AhmedAdelIbrahim  @som3a123  @mahatalaat  @MariamTalaat  
Please review

### CODE REVIEW

**Comment by MariamTalaat** [comment]
@ebrahim-elgaml Forgotten conflicts in myAccount.html.erb

**Comment by myriameayman** [comment]
@ebrahim-elgaml test review : good job 
scenario review : 1- when adding an email the 2nd label or more is textbox not email 
                            2- emails circles not showing any friends  
el donya awara :P

**Comment by MariamTalaat** [comment]
@ebrahim-elgaml  concerning documentation plz  specify the return values  and variable names

**Comment by ebrahim-elgaml** [comment]
@MariamTalaat  there is no conflicts in myAccount page

**Comment by renadshaaban** [comment]
u r our code prince :smile:  :crown: @ebrahim-elgaml

**Comment by ebrahim-elgaml** [comment]
Thanks renad :dancer:  :dancer:  @renadshaaban

**Pull request merged**
