### PR TITLE
modifying profile page#27

### PR DESCRIPTION
**Pull request by aaelfiky**
@renadshaaban @ebrahim-elgaml please review

### CODE REVIEW

**Comment by ebrahim-elgaml** [comment]
@som3a123  
Please check the following 
*app/assets/stylesheets/application.css lines from line 24 to 675, please check the spaces and fix them all should be aligned the same every block starts at the most left of the page and its body after two tabs from it  
*in app/assets/stylesheets/button.css lines from 75 to 94  should be aligned the same pus add a new line after line 94

**Comment by aaelfiky** [comment]
@ebrahim-elgaml Done, please re-check the lines

**Comment by ebrahim-elgaml** [comment]
Great work

**Comment by renadshaaban** [comment]
@som3a123 Good work , I like the colors

**Comment by aaelfiky** [comment]
@myriameayman review done

**Pull request merged**
