### PR TITLE
Join specific trip

### PR DESCRIPTION
**Pull request by renadshaaban**
@ebrahim-elgaml  @AhmedAdelIbrahim  @myriameayman  @mahatalaat  @som3a123 @MariamTalaat plz review this issue

### CODE REVIEW

**Comment by myriameayman** [comment]
:+1:  scenario review

**Comment by aaelfiky** [comment]
@renadshaaban (Y) done with the UML review

**Comment by myriameayman** [comment]
:+1: test review

**Comment by mahatalaat** [comment]
@renadshaaban line number 4 in trips controller needs to be capitalized 
and in the myaccount view you are missing many closing documentations

**Comment by ebrahim-elgaml** [comment]
@renadshaaban 
done put add only spaces in the body of if in request#index and the method search in request model but good job

**Pull request merged**
