### PR TITLE
Estimate kilometers for a trip #85

### PR DESCRIPTION
**Pull request by aaelfiky**
@myriameayman @ebrahim-elgaml @AhmedAdelIbrahim @renadshaaban @MariamTalaat @mahatalaat please review

### CODE REVIEW

**Comment by ebrahim-elgaml** [comment]
@som3a123  
*\* app/controllers/circles_controller.rb index action should move two spaces to the left 
*\* Remove unneeded comments (code commented )
for documentation review (Y)

**Comment by ebrahim-elgaml** [comment]
(Y)

**Comment by AhmedAdelIbrahim** [comment]
@som3a123 done with checking all the tests , all are working

**Comment by renadshaaban** [comment]
@som3a123  done with UML

**Pull request merged**
