### PR TITLE
Search in my friends #69

### PR DESCRIPTION
**Pull request by aaelfiky**
please review @AhmedAdelIbrahim @ebrahim-elgaml @renadshaaban @myriameayman @MariamTalaat @mahatalaat

### CODE REVIEW

**Comment by AhmedAdelIbrahim** [comment]
@som3a123 done with all the tests , all the tests are green

**Comment by renadshaaban** [comment]
done @som3a123

**Comment by myriameayman** [comment]
@som3a123  when i click on a friend's profile i am not redirected to any page

**Comment by aaelfiky** [comment]
that's not my story i swear to god but i can fix it @myriameayman

**Comment by ebrahim-elgaml** [comment]
Dine with code review and documentation review 
@renadshaaban  @som3a123

**Comment by ebrahim-elgaml** [comment]
@myriameayman  or @AhmedAdelIbrahim  scenario review do not forget

**Pull request merged**
