### PR TITLE
Modifying google plus#63

### PR DESCRIPTION
**Pull request by AhmedAdelIbrahim**
@myriameayman @renadshaaban @som3a123 @ebrahim-elgaml @mahatalaat @MariamTalaat Please review me , done with all the requirements.

### CODE REVIEW

**Comment by ebrahim-elgaml** [comment]
@AhmedAdelIbrahim  
*\* please remove all un-needed comments (commented code )
*\* app/controllers/google_controller.rb  line 5 to 17 modify spaces
*\*  app/controllers/google_controller.rb spaces and all (end's) must be aligned under the div
*\*  test/functional/google_controller_test.rb line 12 delete a space

**Comment by AhmedAdelIbrahim** [comment]
@ebrahim-elgaml done , with the requirements

**Comment by ebrahim-elgaml** [comment]
@AhmedAdelIbrahim  again remove unneeded comments

**Comment by ebrahim-elgaml** [comment]
(Y)

**Comment by renadshaaban** [comment]
@AhmedAdelIbrahim Done with UML :dancer:

**Comment by aaelfiky** [comment]
@AhmedAdelIbrahim Done with Documentation :+1:

**Comment by myriameayman** [comment]
@AhmedAdelIbrahim there is a problem in running the test

**Comment by AhmedAdelIbrahim** [comment]
@myriameayman i fixes the problem of the tests

**Comment by myriameayman** [comment]
@AhmedAdelIbrahim  ur tests are not working 
3IB KEDA

**Comment by AhmedAdelIbrahim** [comment]
@myriameayman I fixed the errors check now

**Comment by myriameayman** [comment]
good job :)

**Pull request merged**
