### PR TITLE
View current running trips #72

### PR DESCRIPTION
**Pull request by AhmedAdelIbrahim**
@myriameayman @ebrahim-elgaml @renadshaaban @som3a123 @mahatalaat @MariamTalaat 
Please Review me , finished all the requirements .

### CODE REVIEW

**Comment by myriameayman** [comment]
@AhmedAdelIbrahim with 2 running trips 
only one object is moving 
it will be nice if u can zoom in a little

**Comment by ebrahim-elgaml** [comment]
@AhmedAdelIbrahim  
*\*  app/controllers/requests_controller.rb lines [134 to 143] modify spaces 
*\*  app/views/requests/create_route.html.erb from line 60 to 62  spaces

**Comment by AhmedAdelIbrahim** [comment]
@ebrahim-elgaml done , check now

**Comment by ebrahim-elgaml** [comment]
@AhmedAdelIbrahim  (Y)

**Comment by AhmedAdelIbrahim** [comment]
@myriameayman done , with the zoom , check now

**Comment by aaelfiky** [comment]
documentation :+1:

**Pull request merged**
