### PR TITLE
adding gender to trip and saving current loc #67

### PR DESCRIPTION
**Pull request by myriameayman**

### CODE REVIEW

**Comment by mahatalaat** [comment]
@myriameayman  as you have mentioned nothing to be reviewed here

**Comment by renadshaaban** [comment]
it seems that u dont need a UML here , no job :dancers:

**Comment by AhmedAdelIbrahim** [comment]
@myriameayman I checked the tests and the validations , all are working fine

**Comment by ebrahim-elgaml** [comment]
@myriameayman  
*\* app/views/requests/create.html.erb  from line 52 to 62

**Comment by aaelfiky** [comment]
Scenario :+1:  @myriameayman

**Comment by ebrahim-elgaml** [comment]
done

**Pull request merged**
