### PR TITLE
Drawing routes

### PR DESCRIPTION
**Pull request by myriameayman**

### CODE REVIEW

**Comment by mahatalaat** [comment]
@myriameayman  in the controller part elaborate and in the view part document the missing closing tags

**Comment by myriameayman** [comment]
@mahatalaat  ok ? 
@AhmedAdelIbrahim , @renadshaaban , @ebrahim-elgaml  , @som3a123  plz review me

**Comment by renadshaaban** [comment]
@myriameayman  Done :100:

**Comment by ebrahim-elgaml** [comment]
@myriameayman 
*\* app/views/requests/create_route.html.erb head and body also 
*\*  app/views/requests/delete.html.erb body and head

**Comment by aaelfiky** [comment]
@myriameayman Documentation done , good to go :+1:

**Comment by mahatalaat** [comment]
@myriameayman  perfect :D

**Comment by aaelfiky** [comment]
@myriameayman Scenario done :+1:

**Comment by ebrahim-elgaml** [comment]
Done

**Comment by AhmedAdelIbrahim** [comment]
@myriameayman the test is green , Thank you

**Pull request merged**
