### PR TITLE
generate model request,  places, rating and adding some attributes to us...

### PR DESCRIPTION
**Pull request by myriameayman**
@renadshaaban @ebrahim-elgaml @som3a123 
plz review me

### CODE REVIEW

**Comment by ebrahim-elgaml** [comment]
@myriameayman (  please add two tabs at the start of the line -  remove empty lines  ) and reply back

**Comment by myriameayman** [comment]
@ebrahim-elgaml plz re-review

**Comment by ebrahim-elgaml** [comment]
@myriameayman  
The following needs to be modified :- 
In db/migrate/20150329175316_create_places.rb lines from (3 to 8 ) 
in db/migrate/20150329181908_add_fb_email_to_users.rb line 3
in  db/migrate/20150329182023_add_nickname_to_users.rb line3
in  db/migrate/20150329182422_add_gmail_to_users.r line 3
in   db/migrate/20150329184252_add_budget_to_users.rb_gmail_to_users.r line 3
in  db/migrate/20150329191022_create_visits.rb lines (3-8)

**Comment by renadshaaban** [comment]
@myriameayman  done with scenario review

**Pull request merged**
