### PR TITLE
Adding maps places

### PR DESCRIPTION
**Pull request by myriameayman**

### CODE REVIEW

**Comment by myriameayman** [comment]
@ebrahim-elgaml , @AhmedAdelIbrahim , @renadshaaban , @som3a123 , @mahatalaat   plz review me

**Comment by mahatalaat** [comment]
@myriameayman  in places controller : please leave space between hash and the 1st letter and capitalize it and end it with a dot.

**Comment by myriameayman** [comment]
@maha 
done ?

**Comment by mahatalaat** [comment]
@myriameayman  line number 2 still needs to be Capitalized and add a dot

**Comment by myriameayman** [comment]
@mahatalaat  soory :D 
done :D

**Comment by mahatalaat** [comment]
@myriameayman  done :D

**Comment by renadshaaban** [comment]
@myriameayman  I'm done with the back end (Y)

**Comment by ebrahim-elgaml** [comment]
@myriameayman 
*\* Places controller create action the code needs to be organized in a way better than that the end of the loop the taps every thing please change it and then reply back 
*\* first line in Places#show (two taps need to be removed )
*\* create view the <div class = " form "> part at the end should be all shift to the right by a tap and the end of the loop to the left by space and also there is no documentation for it 
*\* the closing of the body tag in create view should be shifted to the left most of the page 
**show view no documentation for :-
                var placeName = <%= @place.name.to_json.html_safe %>;
                marker 
                map = new google.maps.Map(document.getElementById('map-canvas'),
                  mapOptions);

**Comment by myriameayman** [comment]
@ebrahim-elgaml  plz check again

**Comment by ebrahim-elgaml** [comment]
Fortunately I will put the label
Congratulations @myriameayman

**Pull request merged**
