### PR TITLE
Get facebook friends

### PR DESCRIPTION
**Pull request by ebrahim-elgaml**
@AhmedAdelIbrahim  @myriameayman  @mahatalaat  @renadshaaban  @som3a123 
Review

### CODE REVIEW

**Comment by mahatalaat** [comment]
@ebrahim-elgaml  please add a ( . ) after the documentation

**Comment by ebrahim-elgaml** [comment]
@mahatalaat  Please check now

**Comment by mahatalaat** [comment]
@ebrahim-elgaml  line 32 in Profiles controller MyAccount action add a dot plz

**Comment by mahatalaat** [comment]
@ebrahim-elgaml  done

**Comment by renadshaaban** [comment]
@ebrahim-elgaml plz change UML Diagram name to the user story plz

**Comment by ebrahim-elgaml** [comment]
@renadshaaban  please check now

**Comment by ebrahim-elgaml** [comment]
@renadshaaban  please add the uml review

**Comment by ebrahim-elgaml** [comment]
@myriameayman  please push on master

**Comment by ebrahim-elgaml** [comment]
close issue @myriameayman

**Pull request merged**
