### PR TITLE
Get gender facebook

### PR DESCRIPTION
**Pull request by ebrahim-elgaml**
@AhmedAdelIbrahim  @myriameayman  @mahatalaat  @renadshaaban  @som3a123  Please review

### CODE REVIEW

**Comment by myriameayman** [comment]
done with scenario review

**Comment by aaelfiky** [comment]
@ebrahim-elgaml remove the friend info column in the UML

**Comment by AhmedAdelIbrahim** [comment]
@ebrahim-elgaml please add the test to validate that every user should have a gender , simply in the test file add a validation that the user's gender should not be nil and assert it to true .

**Comment by renadshaaban** [comment]
ur UML is not correct at all (a el3amod ele fl a5er d ?)

**Comment by mahatalaat** [comment]
@ebrahim-elgaml  good job

**Comment by ebrahim-elgaml** [comment]
@AhmedAdelIbrahim  check what you are asking for is bad connection test

**Comment by ebrahim-elgaml** [comment]
@renadshaaban  @som3a123  uml review

**Comment by AhmedAdelIbrahim** [comment]
@ebrahim-elgaml ok , if you are sure that the redirection will always contain the gender

**Comment by aaelfiky** [comment]
@ebrahim-elgaml done UML :+1:

**Comment by renadshaaban** [comment]
I'm done with code review :100:

**Comment by ebrahim-elgaml** [comment]
@myriameayman  merge

**Pull request merged**
