### PR TITLE
Twitter circle

### PR DESCRIPTION
**Pull request by MariamTalaat**
@renadshaaban @som3a123 
plz review

### CODE REVIEW

**Comment by MariamTalaat** [comment]
@renadshaaban @som3a123 
plz review

**Comment by myriameayman** [comment]
@MariamTalaat  NameError in TwitterController#twitter_profile

uninitialized constant TwitterController::Circle
I've got this error once I'm authinticated to twitter , plz fix it

**Comment by MariamTalaat** [comment]
@renadshaaban  @som3a123 
done check again

**Comment by aaelfiky** [comment]
@MariamTalaat it's working fine.

**Pull request merged**
