### PR TITLE
Offering ride

### PR DESCRIPTION
**Pull request by myriameayman**

### CODE REVIEW

**Comment by myriameayman** [comment]
@ebrahim-elgaml, @renadshaaban , @AhmedAdelIbrahim , @som3a123 , @mahatalaat , @MariamTalaat  
plz review me

**Comment by renadshaaban** [comment]
@myriameayman it is okay :+1:

**Comment by AhmedAdelIbrahim** [comment]
@myriameayman Done with the test review and the testing is working fine

**Comment by mahatalaat** [comment]
@myriameayman  in the view request : 

create: line 73 .. its Function not fumction and please add a dot and Capitalize the 1st letter
 line 95 leave space , Capitalize 1st letter and add dot 

gecoding and reverse_gecoding I cant find the documentation 

Home: line 44 and 47 capitalize  and add Dot

**Comment by myriameayman** [comment]
@mahatalaat 
ok ?

**Comment by mahatalaat** [comment]
@myriameayman  perfect :D

**Comment by ebrahim-elgaml** [comment]
@myriameayman  
*_please change the name of variable @@i to another suitable name 
*_Replace every redirect_to "/profiles/myAccount" with root_path beacause you are by that redirecting to show view of profiles with id "myAccount" which will give an error so please change it and run the test again after that 
*_documentation review for geocoding  and reverse-geocoding Actions in requests controller 
*_ remove the commented part inside create_ride_info  Action 
*\* requests#home View the first <br> please remove them and align with CSS
*\* please position the container with percentage because the resolution will  affect the page layout by that 
also the same comment for requests#create view  
*\* replace each redirect_to in request controller with the following [redirect_to url_for(:controller => :controller_name, :action => :action_name)]
Please reply me back when you finish that is for booth code review and documentation review

**Comment by myriameayman** [comment]
@ebrahim-elgaml  check again plz

**Comment by ebrahim-elgaml** [comment]
@myriameayman  Good job 
*_Put please remove the commented parts in each action in request controller
*_in the view please shows values for the padding multiple of 12 to avoid the variety of resolutions 
change [padding-top:500px ] to value multiple of for example (492,504,516)

**Comment by myriameayman** [comment]
@ebrahim-elgaml  check again plz

**Comment by ebrahim-elgaml** [comment]
@myriameayman  please remove line 55,46,78 from requests controllert

**Comment by myriameayman** [comment]
GIVE ME THE LABEL OR I WILL FIND U AND I WILL KILL U 
plz :')

**Comment by ebrahim-elgaml** [comment]
Good job @myriameayman  you are getting familiar with rails code conventions  you deserve it

**Pull request merged**
