### PR TITLE
Sedn mail

### PR DESCRIPTION
**Pull request by ebrahim-elgaml**
@mahatalaat  @AhmedAdelIbrahim  @myriameayman  @renadshaaban  @som3a123  
please review  #84

### CODE REVIEW

**Comment by AhmedAdelIbrahim** [comment]
@ebrahim-elgaml all the tests are green , done with your tests

**Comment by renadshaaban** [comment]
ur code is clean of any mistakes , kefaya zan @ebrahim-elgamal

**Comment by ebrahim-elgaml** [comment]
@myriameayman  done please close issue #84 and merge pull request

**Comment by aaelfiky** [comment]
@ebrahim-elgaml done documentation reviewing :+1:

**Pull request merged**
