### PR TITLE
Invite facebook friends

### PR DESCRIPTION
**Pull request by ebrahim-elgaml**
@AhmedAdelIbrahim  @myriameayman  @mahatalaat  @renadshaaban @som3a123 @MariamTalaat 
Please review me

### CODE REVIEW

**Comment by myriameayman** [comment]
good job :)

**Comment by AhmedAdelIbrahim** [comment]
@ebrahim-elgaml does this user story needs to have tests ?

**Comment by ebrahim-elgaml** [comment]
No

**Comment by AhmedAdelIbrahim** [comment]
@ebrahim-elgaml ok , then there is no tests to check here , Thanks

**Comment by renadshaaban** [comment]
@ebrahim-elgaml  I 'm not able to acces ur branch !

**Comment by ebrahim-elgaml** [comment]
Search again @renadshaaban  do not be lazy

**Comment by mahatalaat** [comment]
@ebrahim-elgaml  in the myAccount view please document the missing parts

**Comment by aaelfiky** [comment]
@ebrahim-elgaml Documentation Done :+1:

**Comment by ebrahim-elgaml** [comment]
@mahatalaat  @som3a123  done with documentation review

**Comment by renadshaaban** [comment]
@ebrahim-elgaml  done with code ;)

**Comment by ebrahim-elgaml** [comment]
@myriameayman  merge

**Pull request merged**
